FROM 3.8.3-alpine3.11

COPY requirements.txt /tmp/

RUN pip install -r /tmp/requirements.txt

RUN useradd --create-home appuser
WORKDIR /home/appuser
USER appuser

COPY fibonacci.py .

ENTRYPOINT [ "python", "./fibonacci.py" ]
CMD ["10"]
