apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apache-hpa
  namespace: kube-system
spec:
  maxReplicas: 2
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: pep-apache
  targetCPUUtilizationPercentage: ".40"
